// Code generated by "generateGoNetworks.ts"; DO NOT EDIT.

package networks

var AllNetworks = []*Network{
	{
		ID: "teritori",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "utori",
				CoinGeckoID: "teritori",
			},
		},
	},
	{
		ID: "teritori-testnet",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "utori",
				CoinGeckoID: "teritori",
			},
			&IBCCurrency{
				Denom:         "ibc/C9300DDD93DF3A3A668CAB02398A0AA081EF89EC005B2DB68832E363BAAABF85",
				SourceNetwork: "cosmos-hub-theta",
				SourceDenom:   "uatom",
			},
			&IBCCurrency{
				Denom:         "ibc/8D9734B53D56DC57A92E4CC788547699853F411190F6DAA70FA12B9BD062F7AE",
				SourceNetwork: "cosmos-hub-theta",
				SourceDenom:   "uatom",
			},
		},
	},
	{
		ID: "cosmos-hub-theta",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "uatom",
				CoinGeckoID: "cosmos",
			},
		},
	},
}
