// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: freelance/v1/freelance.proto

package freelancepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SellerProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SellerAddress string `protobuf:"bytes,1,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
}

func (x *SellerProfileRequest) Reset() {
	*x = SellerProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerProfileRequest) ProtoMessage() {}

func (x *SellerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerProfileRequest.ProtoReflect.Descriptor instead.
func (*SellerProfileRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{0}
}

func (x *SellerProfileRequest) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

type SellerProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SellerAddress string `protobuf:"bytes,1,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	Ipfs          string `protobuf:"bytes,2,opt,name=ipfs,proto3" json:"ipfs,omitempty"`
	IsActive      bool   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *SellerProfileResponse) Reset() {
	*x = SellerProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerProfileResponse) ProtoMessage() {}

func (x *SellerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerProfileResponse.ProtoReflect.Descriptor instead.
func (*SellerProfileResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{1}
}

func (x *SellerProfileResponse) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *SellerProfileResponse) GetIpfs() string {
	if x != nil {
		return x.Ipfs
	}
	return ""
}

func (x *SellerProfileResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GigListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GigListRequest) Reset() {
	*x = GigListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigListRequest) ProtoMessage() {}

func (x *GigListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigListRequest.ProtoReflect.Descriptor instead.
func (*GigListRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{2}
}

func (x *GigListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GigListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GigListUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GigListUserRequest) Reset() {
	*x = GigListUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigListUserRequest) ProtoMessage() {}

func (x *GigListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigListUserRequest.ProtoReflect.Descriptor instead.
func (*GigListUserRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{3}
}

func (x *GigListUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EscrowAllListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EscrowAllListRequest) Reset() {
	*x = EscrowAllListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowAllListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowAllListRequest) ProtoMessage() {}

func (x *EscrowAllListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowAllListRequest.ProtoReflect.Descriptor instead.
func (*EscrowAllListRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{4}
}

func (x *EscrowAllListRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EscrowSenderListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EscrowSenderListRequest) Reset() {
	*x = EscrowSenderListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowSenderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowSenderListRequest) ProtoMessage() {}

func (x *EscrowSenderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowSenderListRequest.ProtoReflect.Descriptor instead.
func (*EscrowSenderListRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{5}
}

func (x *EscrowSenderListRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EscrowReceiverListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EscrowReceiverListRequest) Reset() {
	*x = EscrowReceiverListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowReceiverListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowReceiverListRequest) ProtoMessage() {}

func (x *EscrowReceiverListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowReceiverListRequest.ProtoReflect.Descriptor instead.
func (*EscrowReceiverListRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{6}
}

func (x *EscrowReceiverListRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EscrowInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender      string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver    string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount      string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountDenom string `protobuf:"bytes,5,opt,name=amount_denom,json=amountDenom,proto3" json:"amount_denom,omitempty"`
	ExpireAt    uint64 `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Status      uint32 `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *EscrowInfo) Reset() {
	*x = EscrowInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowInfo) ProtoMessage() {}

func (x *EscrowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowInfo.ProtoReflect.Descriptor instead.
func (*EscrowInfo) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{7}
}

func (x *EscrowInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EscrowInfo) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *EscrowInfo) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *EscrowInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *EscrowInfo) GetAmountDenom() string {
	if x != nil {
		return x.AmountDenom
	}
	return ""
}

func (x *EscrowInfo) GetExpireAt() uint64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *EscrowInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type EscrowAllListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Escrows []*EscrowInfo `protobuf:"bytes,1,rep,name=escrows,proto3" json:"escrows,omitempty"`
}

func (x *EscrowAllListResponse) Reset() {
	*x = EscrowAllListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowAllListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowAllListResponse) ProtoMessage() {}

func (x *EscrowAllListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowAllListResponse.ProtoReflect.Descriptor instead.
func (*EscrowAllListResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{8}
}

func (x *EscrowAllListResponse) GetEscrows() []*EscrowInfo {
	if x != nil {
		return x.Escrows
	}
	return nil
}

type EscrowSenderListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Escrows []*EscrowInfo `protobuf:"bytes,1,rep,name=escrows,proto3" json:"escrows,omitempty"`
}

func (x *EscrowSenderListResponse) Reset() {
	*x = EscrowSenderListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowSenderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowSenderListResponse) ProtoMessage() {}

func (x *EscrowSenderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowSenderListResponse.ProtoReflect.Descriptor instead.
func (*EscrowSenderListResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{9}
}

func (x *EscrowSenderListResponse) GetEscrows() []*EscrowInfo {
	if x != nil {
		return x.Escrows
	}
	return nil
}

type EscrowReceiverListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Escrows []*EscrowInfo `protobuf:"bytes,1,rep,name=escrows,proto3" json:"escrows,omitempty"`
}

func (x *EscrowReceiverListResponse) Reset() {
	*x = EscrowReceiverListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowReceiverListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowReceiverListResponse) ProtoMessage() {}

func (x *EscrowReceiverListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowReceiverListResponse.ProtoReflect.Descriptor instead.
func (*EscrowReceiverListResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{10}
}

func (x *EscrowReceiverListResponse) GetEscrows() []*EscrowInfo {
	if x != nil {
		return x.Escrows
	}
	return nil
}

type GigInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	GigData string `protobuf:"bytes,3,opt,name=gig_data,json=gigData,proto3" json:"gig_data,omitempty"`
}

func (x *GigInfo) Reset() {
	*x = GigInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigInfo) ProtoMessage() {}

func (x *GigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigInfo.ProtoReflect.Descriptor instead.
func (*GigInfo) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{11}
}

func (x *GigInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GigInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GigInfo) GetGigData() string {
	if x != nil {
		return x.GigData
	}
	return ""
}

type GigListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gigs []*GigInfo `protobuf:"bytes,1,rep,name=gigs,proto3" json:"gigs,omitempty"`
}

func (x *GigListResponse) Reset() {
	*x = GigListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigListResponse) ProtoMessage() {}

func (x *GigListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigListResponse.ProtoReflect.Descriptor instead.
func (*GigListResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{12}
}

func (x *GigListResponse) GetGigs() []*GigInfo {
	if x != nil {
		return x.Gigs
	}
	return nil
}

type GigListUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gigs []*GigInfo `protobuf:"bytes,1,rep,name=gigs,proto3" json:"gigs,omitempty"`
}

func (x *GigListUserResponse) Reset() {
	*x = GigListUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigListUserResponse) ProtoMessage() {}

func (x *GigListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigListUserResponse.ProtoReflect.Descriptor instead.
func (*GigListUserResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{13}
}

func (x *GigListUserResponse) GetGigs() []*GigInfo {
	if x != nil {
		return x.Gigs
	}
	return nil
}

type GigDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GigDataRequest) Reset() {
	*x = GigDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigDataRequest) ProtoMessage() {}

func (x *GigDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigDataRequest.ProtoReflect.Descriptor instead.
func (*GigDataRequest) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{14}
}

func (x *GigDataRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GigDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gig *GigInfo `protobuf:"bytes,1,opt,name=gig,proto3" json:"gig,omitempty"`
}

func (x *GigDataResponse) Reset() {
	*x = GigDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freelance_v1_freelance_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigDataResponse) ProtoMessage() {}

func (x *GigDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freelance_v1_freelance_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigDataResponse.ProtoReflect.Descriptor instead.
func (*GigDataResponse) Descriptor() ([]byte, []int) {
	return file_freelance_v1_freelance_proto_rawDescGZIP(), []int{15}
}

func (x *GigDataResponse) GetGig() *GigInfo {
	if x != nil {
		return x.Gig
	}
	return nil
}

var File_freelance_v1_freelance_proto protoreflect.FileDescriptor

var file_freelance_v1_freelance_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x14,
	0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x6f, 0x0a, 0x15, 0x53,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x70, 0x66, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x66, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x3e, 0x0a, 0x0e,
	0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x12,
	0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x30, 0x0a, 0x14,
	0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x33,
	0x0a, 0x17, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x19, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x45,
	0x73, 0x63, 0x72, 0x6f, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a,
	0x15, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x4e, 0x0a, 0x18, 0x45, 0x73,
	0x63, 0x72, 0x6f, 0x77, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x50, 0x0a, 0x1a, 0x45, 0x73,
	0x63, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x65, 0x65,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x4e, 0x0a, 0x07,
	0x47, 0x69, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x69, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x0f,
	0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x29, 0x0a, 0x04, 0x67, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x69, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x67, 0x69, 0x67, 0x73, 0x22, 0x40, 0x0a, 0x13, 0x47, 0x69,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x04, 0x67, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x69, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x67, 0x69, 0x67, 0x73, 0x22, 0x20, 0x0a, 0x0e,
	0x47, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a,
	0x0a, 0x0f, 0x47, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x03, 0x67, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x69,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x67, 0x69, 0x67, 0x32, 0xf6, 0x04, 0x0a, 0x10, 0x46,
	0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x58, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x22, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x69, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x20, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x69,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a,
	0x0d, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22,
	0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73,
	0x63, 0x72, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x10, 0x45, 0x73, 0x63, 0x72, 0x6f,
	0x77, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x66, 0x72,
	0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f,
	0x77, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x12, 0x45, 0x73,
	0x63, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x27, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x66, 0x72, 0x65, 0x65,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_freelance_v1_freelance_proto_rawDescOnce sync.Once
	file_freelance_v1_freelance_proto_rawDescData = file_freelance_v1_freelance_proto_rawDesc
)

func file_freelance_v1_freelance_proto_rawDescGZIP() []byte {
	file_freelance_v1_freelance_proto_rawDescOnce.Do(func() {
		file_freelance_v1_freelance_proto_rawDescData = protoimpl.X.CompressGZIP(file_freelance_v1_freelance_proto_rawDescData)
	})
	return file_freelance_v1_freelance_proto_rawDescData
}

var file_freelance_v1_freelance_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_freelance_v1_freelance_proto_goTypes = []interface{}{
	(*SellerProfileRequest)(nil),       // 0: freelance.v1.SellerProfileRequest
	(*SellerProfileResponse)(nil),      // 1: freelance.v1.SellerProfileResponse
	(*GigListRequest)(nil),             // 2: freelance.v1.GigListRequest
	(*GigListUserRequest)(nil),         // 3: freelance.v1.GigListUserRequest
	(*EscrowAllListRequest)(nil),       // 4: freelance.v1.EscrowAllListRequest
	(*EscrowSenderListRequest)(nil),    // 5: freelance.v1.EscrowSenderListRequest
	(*EscrowReceiverListRequest)(nil),  // 6: freelance.v1.EscrowReceiverListRequest
	(*EscrowInfo)(nil),                 // 7: freelance.v1.EscrowInfo
	(*EscrowAllListResponse)(nil),      // 8: freelance.v1.EscrowAllListResponse
	(*EscrowSenderListResponse)(nil),   // 9: freelance.v1.EscrowSenderListResponse
	(*EscrowReceiverListResponse)(nil), // 10: freelance.v1.EscrowReceiverListResponse
	(*GigInfo)(nil),                    // 11: freelance.v1.GigInfo
	(*GigListResponse)(nil),            // 12: freelance.v1.GigListResponse
	(*GigListUserResponse)(nil),        // 13: freelance.v1.GigListUserResponse
	(*GigDataRequest)(nil),             // 14: freelance.v1.GigDataRequest
	(*GigDataResponse)(nil),            // 15: freelance.v1.GigDataResponse
}
var file_freelance_v1_freelance_proto_depIdxs = []int32{
	7,  // 0: freelance.v1.EscrowAllListResponse.escrows:type_name -> freelance.v1.EscrowInfo
	7,  // 1: freelance.v1.EscrowSenderListResponse.escrows:type_name -> freelance.v1.EscrowInfo
	7,  // 2: freelance.v1.EscrowReceiverListResponse.escrows:type_name -> freelance.v1.EscrowInfo
	11, // 3: freelance.v1.GigListResponse.gigs:type_name -> freelance.v1.GigInfo
	11, // 4: freelance.v1.GigListUserResponse.gigs:type_name -> freelance.v1.GigInfo
	11, // 5: freelance.v1.GigDataResponse.gig:type_name -> freelance.v1.GigInfo
	0,  // 6: freelance.v1.FreelanceService.SellerProfile:input_type -> freelance.v1.SellerProfileRequest
	2,  // 7: freelance.v1.FreelanceService.GigList:input_type -> freelance.v1.GigListRequest
	3,  // 8: freelance.v1.FreelanceService.GigListUser:input_type -> freelance.v1.GigListUserRequest
	14, // 9: freelance.v1.FreelanceService.GigData:input_type -> freelance.v1.GigDataRequest
	4,  // 10: freelance.v1.FreelanceService.EscrowAllList:input_type -> freelance.v1.EscrowAllListRequest
	5,  // 11: freelance.v1.FreelanceService.EscrowSenderList:input_type -> freelance.v1.EscrowSenderListRequest
	6,  // 12: freelance.v1.FreelanceService.EscrowReceiverList:input_type -> freelance.v1.EscrowReceiverListRequest
	1,  // 13: freelance.v1.FreelanceService.SellerProfile:output_type -> freelance.v1.SellerProfileResponse
	12, // 14: freelance.v1.FreelanceService.GigList:output_type -> freelance.v1.GigListResponse
	13, // 15: freelance.v1.FreelanceService.GigListUser:output_type -> freelance.v1.GigListUserResponse
	15, // 16: freelance.v1.FreelanceService.GigData:output_type -> freelance.v1.GigDataResponse
	8,  // 17: freelance.v1.FreelanceService.EscrowAllList:output_type -> freelance.v1.EscrowAllListResponse
	9,  // 18: freelance.v1.FreelanceService.EscrowSenderList:output_type -> freelance.v1.EscrowSenderListResponse
	10, // 19: freelance.v1.FreelanceService.EscrowReceiverList:output_type -> freelance.v1.EscrowReceiverListResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_freelance_v1_freelance_proto_init() }
func file_freelance_v1_freelance_proto_init() {
	if File_freelance_v1_freelance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_freelance_v1_freelance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellerProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellerProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigListUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowAllListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowSenderListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowReceiverListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowAllListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowSenderListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowReceiverListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigListUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freelance_v1_freelance_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_freelance_v1_freelance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_freelance_v1_freelance_proto_goTypes,
		DependencyIndexes: file_freelance_v1_freelance_proto_depIdxs,
		MessageInfos:      file_freelance_v1_freelance_proto_msgTypes,
	}.Build()
	File_freelance_v1_freelance_proto = out.File
	file_freelance_v1_freelance_proto_rawDesc = nil
	file_freelance_v1_freelance_proto_goTypes = nil
	file_freelance_v1_freelance_proto_depIdxs = nil
}
