import {
  currencyATOMcolor,
  currencyOSMOcolor,
  currencyTORIcolor,
} from "../../utils/style/colors";
import { NetworkName } from "../NetworkName";
import { NativeCurrencyInfo } from "../types";

export const allNativeCurrencies: NativeCurrencyInfo[] = [
  {
    denom: "uatom",
    displayName: "ATOM",
    sourceNetworkDisplayName: NetworkName.CosmosHub,
    decimals: 6,
    coingeckoId: "cosmos",
    icon: "icons/networks/cosmos-hub-circle.svg",
    kind: "native",
    color: currencyATOMcolor,
  },
  {
    denom: "uatom",
    displayName: "ATOM",
    sourceNetworkDisplayName: NetworkName.CosmosHubTheta,
    decimals: 6,
    coingeckoId: "cosmos",
    icon: "icons/networks/cosmos-hub-circle.svg",
    kind: "native",
    color: currencyATOMcolor,
  },
  {
    denom: "x",
    displayName: "x",
    sourceNetworkDisplayName: NetworkName.Ethereum,
    decimals: 6,
    coingeckoId: "ethereum",
    icon: "icons/networks/ethereum-circle.svg",
    kind: "native",
    color: "#FFFFFF",
  },
  {
    denom: "ujuno",
    displayName: "JUNO",
    sourceNetworkDisplayName: NetworkName.Juno,
    decimals: 6,
    coingeckoId: "juno-network",
    icon: "icons/networks/juno-circle.svg",
    kind: "native",
    color: "#FFFFFF",
  },
  {
    denom: "uosmo",
    displayName: "OSMO",
    sourceNetworkDisplayName: NetworkName.Osmosis,
    decimals: 6,
    coingeckoId: "osmosis",
    icon: "icons/networks/osmosis-circle.svg",
    kind: "native",
    color: currencyOSMOcolor,
  },
  {
    denom: "uosmo",
    displayName: "OSMO",
    sourceNetworkDisplayName: NetworkName.OsmosisTestnet,
    decimals: 6,
    coingeckoId: "osmosis",
    icon: "icons/networks/osmosis-circle.svg",
    kind: "native",
    color: currencyOSMOcolor,
  },
  {
    denom: "x",
    displayName: "x",
    sourceNetworkDisplayName: NetworkName.Solana,
    decimals: 6,
    coingeckoId: "solana",
    icon: "icons/networks/solana-circle.svg",
    kind: "native",
    color: "#FFFFFF",
  },
  {
    denom: "utori",
    displayName: "TORI",
    sourceNetworkDisplayName: NetworkName.Teritori,
    decimals: 6,
    coingeckoId: "teritori",
    icon: "icons/networks/teritori-circle.svg",
    kind: "native",
    color: currencyTORIcolor,
  },
  {
    denom: "utori",
    displayName: "TORI",
    sourceNetworkDisplayName: NetworkName.TeritoriTestnet,
    decimals: 6,
    coingeckoId: "teritori",
    icon: "icons/networks/teritori-circle.svg",
    kind: "native",
    color: currencyTORIcolor,
  },
];
