export const SQUAD_STAKE_COEF = 0.125;

export const THE_RIOT_SQUAD_STAKING_CONTRACT_ADDRESS =
  process.env.THE_RIOT_SQUAD_STAKING_CONTRACT_ADDRESS || "";

export const THE_RIOT_COLLECTION_ADDRESS =
  process.env.THE_RIOT_COLLECTION_ADDRESS || "";

export const THE_RIOT_COLLECTION_ID = `tori-${THE_RIOT_COLLECTION_ADDRESS}`;

export const THE_RIOT_BREEDING_CONTRACT_ADDRESS =
  process.env.THE_RIOT_BREEDING_CONTRACT_ADDRESS || "";

export const THE_RIOT_BREEDING_CHILD_CONTRACT_ADDRESS =
  process.env.THE_RIOT_BREEDING_CHILD_CONTRACT_ADDRESS || "";
