// source: verifiablecredstypes/bertyverifiablecreds.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var gogoproto_gogo_pb = require('../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.weshnet.account.v1.AccountCryptoChallenge', null, global);
goog.exportSymbol('proto.weshnet.account.v1.CodeStrategy', null, global);
goog.exportSymbol('proto.weshnet.account.v1.FlowType', null, global);
goog.exportSymbol('proto.weshnet.account.v1.StateChallenge', null, global);
goog.exportSymbol('proto.weshnet.account.v1.StateCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weshnet.account.v1.StateChallenge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weshnet.account.v1.StateChallenge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weshnet.account.v1.StateChallenge.displayName = 'proto.weshnet.account.v1.StateChallenge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weshnet.account.v1.StateCode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weshnet.account.v1.StateCode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weshnet.account.v1.StateCode.displayName = 'proto.weshnet.account.v1.StateCode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weshnet.account.v1.AccountCryptoChallenge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weshnet.account.v1.AccountCryptoChallenge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weshnet.account.v1.AccountCryptoChallenge.displayName = 'proto.weshnet.account.v1.AccountCryptoChallenge';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weshnet.account.v1.StateChallenge.prototype.toObject = function(opt_includeInstance) {
  return proto.weshnet.account.v1.StateChallenge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weshnet.account.v1.StateChallenge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weshnet.account.v1.StateChallenge.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: msg.getTimestamp_asB64(),
    nonce: msg.getNonce_asB64(),
    bertyLink: jspb.Message.getFieldWithDefault(msg, 3, ""),
    redirectUri: jspb.Message.getFieldWithDefault(msg, 4, ""),
    state: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weshnet.account.v1.StateChallenge}
 */
proto.weshnet.account.v1.StateChallenge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weshnet.account.v1.StateChallenge;
  return proto.weshnet.account.v1.StateChallenge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weshnet.account.v1.StateChallenge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weshnet.account.v1.StateChallenge}
 */
proto.weshnet.account.v1.StateChallenge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNonce(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBertyLink(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirectUri(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weshnet.account.v1.StateChallenge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weshnet.account.v1.StateChallenge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weshnet.account.v1.StateChallenge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weshnet.account.v1.StateChallenge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getNonce_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getBertyLink();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRedirectUri();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional bytes timestamp = 1;
 * @return {!(string|Uint8Array)}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getTimestamp = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes timestamp = 1;
 * This is a type-conversion wrapper around `getTimestamp()`
 * @return {string}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getTimestamp_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTimestamp()));
};


/**
 * optional bytes timestamp = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTimestamp()`
 * @return {!Uint8Array}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getTimestamp_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTimestamp()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.weshnet.account.v1.StateChallenge} returns this
 */
proto.weshnet.account.v1.StateChallenge.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes nonce = 2;
 * @return {!(string|Uint8Array)}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getNonce = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes nonce = 2;
 * This is a type-conversion wrapper around `getNonce()`
 * @return {string}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getNonce_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNonce()));
};


/**
 * optional bytes nonce = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNonce()`
 * @return {!Uint8Array}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getNonce_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNonce()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.weshnet.account.v1.StateChallenge} returns this
 */
proto.weshnet.account.v1.StateChallenge.prototype.setNonce = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional string berty_link = 3;
 * @return {string}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getBertyLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateChallenge} returns this
 */
proto.weshnet.account.v1.StateChallenge.prototype.setBertyLink = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string redirect_uri = 4;
 * @return {string}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getRedirectUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateChallenge} returns this
 */
proto.weshnet.account.v1.StateChallenge.prototype.setRedirectUri = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string state = 5;
 * @return {string}
 */
proto.weshnet.account.v1.StateChallenge.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateChallenge} returns this
 */
proto.weshnet.account.v1.StateChallenge.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weshnet.account.v1.StateCode.prototype.toObject = function(opt_includeInstance) {
  return proto.weshnet.account.v1.StateCode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weshnet.account.v1.StateCode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weshnet.account.v1.StateCode.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: msg.getTimestamp_asB64(),
    bertyLink: jspb.Message.getFieldWithDefault(msg, 2, ""),
    codeStrategy: jspb.Message.getFieldWithDefault(msg, 3, 0),
    identifier: jspb.Message.getFieldWithDefault(msg, 4, ""),
    code: jspb.Message.getFieldWithDefault(msg, 5, ""),
    redirectUri: jspb.Message.getFieldWithDefault(msg, 6, ""),
    state: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weshnet.account.v1.StateCode}
 */
proto.weshnet.account.v1.StateCode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weshnet.account.v1.StateCode;
  return proto.weshnet.account.v1.StateCode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weshnet.account.v1.StateCode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weshnet.account.v1.StateCode}
 */
proto.weshnet.account.v1.StateCode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBertyLink(value);
      break;
    case 3:
      var value = /** @type {!proto.weshnet.account.v1.CodeStrategy} */ (reader.readEnum());
      msg.setCodeStrategy(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentifier(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirectUri(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weshnet.account.v1.StateCode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weshnet.account.v1.StateCode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weshnet.account.v1.StateCode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weshnet.account.v1.StateCode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getBertyLink();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCodeStrategy();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getIdentifier();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRedirectUri();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional bytes timestamp = 1;
 * @return {!(string|Uint8Array)}
 */
proto.weshnet.account.v1.StateCode.prototype.getTimestamp = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes timestamp = 1;
 * This is a type-conversion wrapper around `getTimestamp()`
 * @return {string}
 */
proto.weshnet.account.v1.StateCode.prototype.getTimestamp_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTimestamp()));
};


/**
 * optional bytes timestamp = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTimestamp()`
 * @return {!Uint8Array}
 */
proto.weshnet.account.v1.StateCode.prototype.getTimestamp_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTimestamp()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string berty_link = 2;
 * @return {string}
 */
proto.weshnet.account.v1.StateCode.prototype.getBertyLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setBertyLink = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional CodeStrategy code_strategy = 3;
 * @return {!proto.weshnet.account.v1.CodeStrategy}
 */
proto.weshnet.account.v1.StateCode.prototype.getCodeStrategy = function() {
  return /** @type {!proto.weshnet.account.v1.CodeStrategy} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.weshnet.account.v1.CodeStrategy} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setCodeStrategy = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string identifier = 4;
 * @return {string}
 */
proto.weshnet.account.v1.StateCode.prototype.getIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setIdentifier = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string code = 5;
 * @return {string}
 */
proto.weshnet.account.v1.StateCode.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string redirect_uri = 6;
 * @return {string}
 */
proto.weshnet.account.v1.StateCode.prototype.getRedirectUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setRedirectUri = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string state = 7;
 * @return {string}
 */
proto.weshnet.account.v1.StateCode.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.StateCode} returns this
 */
proto.weshnet.account.v1.StateCode.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weshnet.account.v1.AccountCryptoChallenge.prototype.toObject = function(opt_includeInstance) {
  return proto.weshnet.account.v1.AccountCryptoChallenge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weshnet.account.v1.AccountCryptoChallenge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weshnet.account.v1.AccountCryptoChallenge.toObject = function(includeInstance, msg) {
  var f, obj = {
    challenge: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weshnet.account.v1.AccountCryptoChallenge}
 */
proto.weshnet.account.v1.AccountCryptoChallenge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weshnet.account.v1.AccountCryptoChallenge;
  return proto.weshnet.account.v1.AccountCryptoChallenge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weshnet.account.v1.AccountCryptoChallenge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weshnet.account.v1.AccountCryptoChallenge}
 */
proto.weshnet.account.v1.AccountCryptoChallenge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChallenge(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weshnet.account.v1.AccountCryptoChallenge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weshnet.account.v1.AccountCryptoChallenge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weshnet.account.v1.AccountCryptoChallenge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weshnet.account.v1.AccountCryptoChallenge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChallenge();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string challenge = 1;
 * @return {string}
 */
proto.weshnet.account.v1.AccountCryptoChallenge.prototype.getChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.weshnet.account.v1.AccountCryptoChallenge} returns this
 */
proto.weshnet.account.v1.AccountCryptoChallenge.prototype.setChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.weshnet.account.v1.FlowType = {
  FLOWTYPEUNDEFINED: 0,
  FLOWTYPECODE: 1,
  FLOWTYPEAUTH: 2,
  FLOWTYPEPROOF: 3
};

/**
 * @enum {number}
 */
proto.weshnet.account.v1.CodeStrategy = {
  CODESTRATEGYUNDEFINED: 0,
  CODESTRATEGY6DIGITS: 1,
  CODESTRATEGY10CHARS: 2,
  CODESTRATEGYMOCKED6ZEROES: 999
};

goog.object.extend(exports, proto.weshnet.account.v1);
