// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,json_types=true"
// @generated from file polls/v1/polls.proto (package polls.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "../../libs/protobuf-codegenv2.ts";
import { enumDesc, fileDesc, messageDesc } from "../../libs/protobuf-codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file polls/v1/polls.proto.
 */
export const file_polls_v1_polls: GenFile = /*@__PURE__*/
  fileDesc("ChRwb2xscy92MS9wb2xscy5wcm90bxIIcG9sbHMudjEiQwoKUG9sbFJlc3VsdBIOCgZvcHRpb24YASABKAkSDQoFY291bnQYAiABKA0SFgoOaGFzX3VzZXJfdm90ZWQYAyABKAgimwEKBFBvbGwSEAoIcXVlc3Rpb24YASABKAkSJQoHcmVzdWx0cxgCIAMoCzIULnBvbGxzLnYxLlBvbGxSZXN1bHQSIAoEa2luZBgDIAEoDjISLnBvbGxzLnYxLlBvbGxLaW5kEhAKCGR1cmF0aW9uGAQgASgDEhIKCmNyZWF0ZWRfYXQYBSABKAMSEgoKY3JlYXRlZF9ieRgGIAEoCSphCghQb2xsS2luZBIZChVQT0xMX0tJTkRfVU5TUEVDSUZJRUQQABIbChdQT0xMX0tJTkRfU0lOR0xFX0NIT0lDRRABEh0KGVBPTExfS0lORF9NVUxUSVBMRV9DSE9JQ0UQAkI5WjdnaXRodWIuY29tL3NhbW91cmFpd29ybGQvemVuYW8vYmFja2VuZC9wb2xscy92MTtwb2xsc3YxYgZwcm90bzM");

/**
 * @generated from message polls.v1.PollResult
 */
export type PollResult = Message<"polls.v1.PollResult"> & {
  /**
   * @generated from field: string option = 1;
   */
  option: string;

  /**
   * @generated from field: uint32 count = 2;
   */
  count: number;

  /**
   * @generated from field: bool has_user_voted = 3;
   */
  hasUserVoted: boolean;
};

/**
 * @generated from message polls.v1.PollResult
 */
export type PollResultJson = {
  /**
   * @generated from field: string option = 1;
   */
  option?: string;

  /**
   * @generated from field: uint32 count = 2;
   */
  count?: number;

  /**
   * @generated from field: bool has_user_voted = 3;
   */
  hasUserVoted?: boolean;
};

/**
 * Describes the message polls.v1.PollResult.
 * Use `create(PollResultSchema)` to create a new message.
 */
export const PollResultSchema: GenMessage<PollResult, {jsonType: PollResultJson}> = /*@__PURE__*/
  messageDesc(file_polls_v1_polls, 0);

/**
 * @generated from message polls.v1.Poll
 */
export type Poll = Message<"polls.v1.Poll"> & {
  /**
   * @generated from field: string question = 1;
   */
  question: string;

  /**
   * @generated from field: repeated polls.v1.PollResult results = 2;
   */
  results: PollResult[];

  /**
   * @generated from field: polls.v1.PollKind kind = 3;
   */
  kind: PollKind;

  /**
   * @generated from field: int64 duration = 4;
   */
  duration: bigint;

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;

  /**
   * @generated from field: string created_by = 6;
   */
  createdBy: string;
};

/**
 * @generated from message polls.v1.Poll
 */
export type PollJson = {
  /**
   * @generated from field: string question = 1;
   */
  question?: string;

  /**
   * @generated from field: repeated polls.v1.PollResult results = 2;
   */
  results?: PollResultJson[];

  /**
   * @generated from field: polls.v1.PollKind kind = 3;
   */
  kind?: PollKindJson;

  /**
   * @generated from field: int64 duration = 4;
   */
  duration?: string;

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt?: string;

  /**
   * @generated from field: string created_by = 6;
   */
  createdBy?: string;
};

/**
 * Describes the message polls.v1.Poll.
 * Use `create(PollSchema)` to create a new message.
 */
export const PollSchema: GenMessage<Poll, {jsonType: PollJson}> = /*@__PURE__*/
  messageDesc(file_polls_v1_polls, 1);

/**
 * @generated from enum polls.v1.PollKind
 */
export enum PollKind {
  /**
   * @generated from enum value: POLL_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POLL_KIND_SINGLE_CHOICE = 1;
   */
  SINGLE_CHOICE = 1,

  /**
   * @generated from enum value: POLL_KIND_MULTIPLE_CHOICE = 2;
   */
  MULTIPLE_CHOICE = 2,
}

/**
 * @generated from enum polls.v1.PollKind
 */
export type PollKindJson = "POLL_KIND_UNSPECIFIED" | "POLL_KIND_SINGLE_CHOICE" | "POLL_KIND_MULTIPLE_CHOICE";

/**
 * Describes the enum polls.v1.PollKind.
 */
export const PollKindSchema: GenEnum<PollKind, PollKindJson> = /*@__PURE__*/
  enumDesc(file_polls_v1_polls, 0);

