import { fullSidebarWidth } from "../../utils/style/layout";

export const ASSET_RATIO_WIDTH = 372;
export const ASSET_RATIO_MARGIN_RIGHT = 32;
const WALLET_SCREEN_CONTAINER_MARGIN_HORIZONTAL = 32;
export const TOKEN_ALLOCATION_WIDTH = 498;
export const OVERVIEW_FLEX_BREAK_WIDTH =
  ASSET_RATIO_WIDTH +
  TOKEN_ALLOCATION_WIDTH +
  fullSidebarWidth +
  ASSET_RATIO_MARGIN_RIGHT +
  WALLET_SCREEN_CONTAINER_MARGIN_HORIZONTAL * 2;
