//@ts-nocheck

/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.25.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Addr = string;
export interface Config {
  owner: Addr;
  [k: string]: unknown;
}
export type ExecuteMsg =
  | {
      update_config: {
        owner?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      update_fee_by_category: {
        category: number;
        fee: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      add_free_posts: {
        free_count: Uint128;
        wallets: string[];
        [k: string]: unknown;
      };
    }
  | {
      create_music_album: {
        category: number;
        identifier: string;
        metadata: string;
        [k: string]: unknown;
      };
    }
  | {
      lock_tokens: {
        [k: string]: unknown;
      };
    }
  | {
      unlock_tokens: {
        amount: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      withdraw_fund: {
        [k: string]: unknown;
      };
    };
export type Uint128 = string;
export interface InstantiateMsg {
  [k: string]: unknown;
}
export type MusicAlbumCategory =  | "Normal";
export interface MusicAlbumResult {
  category: number;
  deleted: boolean;
  identifier: string;
  metadata: string;
  post_by: Addr;
  [k: string]: unknown;
}
export interface MusicAlbum {
  category: number;
  deleted: boolean;
  fee_amount: Uint128;
  identifier: string;
  is_free: boolean;
  metadata: string;
  post_by: Addr;
  [k: string]: unknown;
}
export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      query_fee_by_category: {
        category: number;
        [k: string]: unknown;
      };
    }
  | {
      query_locked_tokens: {
        wallet: string;
        [k: string]: unknown;
      };
    }
  | {
      query_available_free_posts: {
        wallet: string;
        [k: string]: unknown;
      };
    }
  | {
      query_music_album: {
        identifier: string;
        [k: string]: unknown;
      };
    };
