export const textStyle = {
  base: {
    color: "white",
    fontSize: 20,
    fontWeight: "600",
  },
  H1_Bebas_80: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 80,
    lineHeight: 96,
  },
  H1_Bebas_40: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 40,
    lineHeight: 48,
  },
  H1_Bebas_30: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 30,
    lineHeight: 36,
  },
  H2_DHBS_80: {
    fontFamily: "Dafter Harder Better Stronger",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 80,
    lineHeight: 96,
  },
  H2_DHBS_40: {
    fontFamily: "Dafter Harder Better Stronger",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 40,
    lineHeight: 48,
  },
  H2_DHBS_30: {
    fontFamily: "Dafter Harder Better Stronger",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 30,
    lineHeight: 35,
  },
  T2_Bebas_50: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 50,
    lineHeight: 48,
  },
  T2_Bebas_20: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 20,
    lineHeight: 48,
  },
  T1_Bebas_20: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 20,
    lineHeight: 24,
  },
  T1_DHBS_20: {
    fontFamily: "Dafter Harder Better Stronger",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 20,
    lineHeight: 48,
  },
  T1_Bebas_15: {
    fontFamily: "Bebas Neue",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 15,
    lineHeight: 18,
  },
};
