// import {
//   INDEXER_NETWORK_ID,
//   TERITORI_MINTER_CODE_IDS,
//   TENDERMINT_WEBSOCKET_ENDPOINT,
//   TERITORI_COLLECTION_WHITELIST,
//   PUBLIC_OPENGRAPH_APP_ID,
//   PUBLIC_TENOR_KEY,
//   P2E_NETWORK_ID,
//   P2E_RPC_ENDPOINT,
//   POSTGRES_USER,
//   POSTGRES_PASSWORD,
//   DATABASE_NAME,
//   DB_INDEXER_HOST,
//   DB_INDEXER_PORT,
//   DB_DAPP_HOST,
//   DB_DAPP_PORT,
//   PRICES_DB_HOST,
//   PRICES_DB_PORT,
//   PRICES_DB_NAME,
//   PRICES_DB_USER,
//   PRICES_DB_PASSWORD,
//   PRICES_SERVICE_URI,
//   DISPLAYED_NETWORKS_IDS,
//   SELECTABLE_NETWORKS_IDS,
//   PINATA_JWT,
// } from "@env";

export const env = {
  INDEXER_NETWORK_ID: process.env.INDEXER_NETWORK_ID,
  TERITORI_MINTER_CODE_IDS: process.env.TERITORI_MINTER_CODE_IDS,
  TENDERMINT_WEBSOCKET_ENDPOINT: process.env.TENDERMINT_WEBSOCKET_ENDPOINT,
  TERITORI_COLLECTION_WHITELIST: process.env.TERITORI_COLLECTION_WHITELIST,

  PUBLIC_OPENGRAPH_APP_ID: process.env.PUBLIC_OPENGRAPH_APP_ID,
  PUBLIC_TENOR_KEY: process.env.PUBLIC_TENOR_KEY,

  P2E_NETWORK_ID: process.env.P2E_NETWORK_ID,
  P2E_RPC_ENDPOINT: process.env.P2E_RPC_ENDPOINT,

  POSTGRES_USER: process.env.POSTGRES_USER,
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
  DATABASE_NAME: process.env.DATABASE_NAME,

  DB_INDEXER_HOST: process.env.DB_INDEXER_HOST,
  DB_INDEXER_PORT: process.env.DB_INDEXER_PORT,

  DB_DAPP_HOST: process.env.DB_DAPP_HOST,
  DB_DAPP_PORT: process.env.DB_DAPP_PORT,

  PRICES_DB_HOST: process.env.PRICES_DB_HOST,
  PRICES_DB_PORT: process.env.PRICES_DB_PORT,
  PRICES_DB_NAME: process.env.PRICES_DB_NAME,
  PRICES_DB_USER: process.env.PRICES_DB_USER,
  PRICES_DB_PASSWORD: process.env.PRICES_DB_PASSWORD,

  PRICES_SERVICE_URI: process.env.PRICES_SERVICE_URI,

  DISPLAYED_NETWORKS_IDS: process.env.DISPLAYED_NETWORKS_IDS,
  SELECTABLE_NETWORKS_IDS: process.env.SELECTABLE_NETWORKS_IDS,

  PINATA_JWT: process.env.PINATA_JWT,
};

console.log("env", env);
