export const NFT_DETAILS_WIDTH = 464;
export const LIST_NFT_FORM_WIDTH = 464;
export const LIST_MY_NFT_COLUMN_MARGIN = 48;
export const BODY_EXTRA_WIDTH = 180;
export const LIST_MY_NFT_FLEX_BREAK_WIDTH =
  NFT_DETAILS_WIDTH +
  LIST_NFT_FORM_WIDTH +
  LIST_MY_NFT_COLUMN_MARGIN +
  BODY_EXTRA_WIDTH;

export const COLUMN_MAX_WIDTH = 600;
