name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14
    continue-on-error: true
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Select xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Fix package.json
        run: yarn remove @lottiefiles/react-lottie-player

      - name: Install node modules
        run: yarn install

      - name: Fix gitignore
        run: npx tsx ./packages/scripts/app-build/fixGitignore.ts

      - name: Build ios weshframework
        run: make check-ios-weshframework

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build ios
        run: eas build --local --non-interactive --platform=ios

      - name: EAS Submit iOS IPA
        run: |
          IPA_FILE=$(find ./ -name 'build-*.ipa' -type f)
          if [ -z "$IPA_FILE" ]; then
            echo "Error: IPA file not found."
            exit 1
          fi

          # eas submit --platform=ios --path=$IPA_FILE 
          echo "IPA_FILE=$IPA_FILE" >> $GITHUB_ENV

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: teritori-${{ github.sha }}.ipa
          path: ${{ env.IPA_FILE }}
          if-no-files-found: error
